### ISSUE TITLE
Allow for extracting a file from an archive by referencing its internal filename only

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#102]
Currently a user must use the internal filename to determine the file's index and then pass the index to extract the file. This should be accomplished by one call to the library.

**Comment by DanRStevens** [comment]
Hmm, I think I'd be willing to accept one-liner as opposed to one-call.

As it stands, it feels like we have too many virtual functions, some being simple glue for the others. I'm wondering if we should reduce the number of virtual methods, and instead replace some with small inline methods? That might not be very interface like, but it seems to make more sense.

This is all just thinking out loud. I may change my mind on this.
