### ISSUE TITLE
Add a namespace to stream library code

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#142]
I was thinking, it might make sense to wrap all the stream code in a namespace called stream. We could also remove stream from the names of the major classes. So it would read:

```
Stream::Reader
Stream::Writer
Stream::SeekableReader
Stream::SeekableWriter
Stream::MemoryReader
Stream::MemoryWriter
Stream::FileReader
Stream::FileWriter
```

The downside to this approach is if you included the using namespace for Stream, you would just see Reader or Writer in the source code, which is too terse. Since it seems like C++ programmers tend to avoid the using statement for namespaces, it might be fine though.

I think this is a good idea, but certainly open for thought or rejection here. 

I think the size of the stream library codebase will continue to grow and it might be nice to segment it now in a namespace.

-Brett

**Comment by DanRStevens** [comment]
I really like this idea.

**Comment by Brett208** [comment]
Cool. I'll implement it then and see how it looks in a branch. This will be sweeping changes to the whole codebase again since it will involve filename changes and class name changes. If you are working on something in the meantime stream related, maybe better if I wait before working on it.

-Brett

**Comment by DanRStevens** [comment]
Huh, I just replied to Issue #139, and my recommendation there was one namespace per library. I suppose that suggestion is technically against doing this. Though there was also discussion about the stream portion being a separate library.

At any rate, go ahead and do this if you want. I'm just noting the discrepancy in my recommendations.

I don't currently have any significant work in progress that I'd expect this change to interfere with.
