### ISSUE TITLE
Unsigned Short typedef in AdaptiveHuffManTree

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#149]
I noticed the typedef defined in the header file for AdaptiveHuffmanTree for unsigned short (USHORT) is not used in the cpp file. Instead of using USHORT, the cpp file uses unsigned short directly. This makes Visual Studio report that it cannot find the function definition (although it compiles fine with MSVC)

I was thinking about removing the typedef from the codebase. I'm assuming that since the typedef is defined in the public portion of the class declaration, it will be visible to any code that includes AdaptiveHuffmanTree, which I think is overall not desirable since if forces the typedef on other's code?

If we want to use it, I guess we should probably unify the class' cpp file to also use USHORT.

Thanks,
Brett

**Comment by DanRStevens** [comment]
Good catch on the inconsistency. Removing the typedef may be a simple way to go. I think the original spirit of the design, was to make it easy to change the underlying data type, which affects memory consumption of the adaptive tree.

In terms of living up to that spirit, using a template would have been more appropriate. However, that would require moving the implementation into the header file.

As for the namespace pollution, the typedef is contained inside the `AdaptiveHuffmanTree` class, and so will be scoped as such. That should negate any namespace pollution issues.

I guess the question is, do we want to permanently fix the data type, or do we want to parameterize it by making the class a template?

**Comment by Brett208** [comment]
What are our long term design goals with the AdaptiveHuffman tree? If this is code only meant to manipulate the vol files, I'd be okay just removing the typedef and calling it a day. 

If this code could eventually be lifted out of the Archives into something more generic, then I would say do it right and put the template together.

-Brett

**Comment by DanRStevens** [comment]
Well, adaptive Huffman trees would be a fairly generic component used by a number of compression algorithms. I am very tempted to keep this one generic. However, this particular implementation may be making a few assumptions which are less desirable in the general case, such as about the range of values stored in the nodes. I don't currently foresee plans to use a generic component of this nature. We could potentially remove the typedef, knowing it would be fairly easy to update the code in the future to make it templated.

I suppose another angle, is maybe the typedef is just really badly named. Perhaps `NodeIndex` and `DataValue` would be better names. Most of the `USHORT` would be a `NodeIndex`. A couple represent a `DataValue`. The reason they share the same type, is the code effectively assumes the two values are contained in a tagged union (though not implemented exactly as such).

Perhaps we should consider splitting and renaming the typedef to `NodeIndex` and `DataValue`, and see how that looks. If we want to make it more generic, the typedef name just becomes a template parameter.

**Comment by Brett208** [comment]
I just wanted to see the function signatures match between the declarations and definitions, so am happy with any solution. I probably do not have enough knowledge of an AdaptiveHuffmanTree to make the changes to use the 2 separate typedefs.

I like the idea of cleaning and improving the AdaptiveHuffmanTree since it is a generic class that could be reused, but it is more time spent on an un-needed refactor.

Would the argument code here: `UpdateCodeCount(USHORT code)` be the DataValue you mentioned?

Thanks,
-Brett

**Comment by DanRStevens** [comment]
Correct. Another example is the return value of `USHORT GetNodeData(USHORT nodeIndex)`. The member variables I might need to think about a bit.

Perhaps I should tackle this issue.
