### ISSUE TITLE
CI should build and run tests

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#155]
The CI jobs should be updated to build and run the tests. The Linux jobs should be easy, with a small tweak to the make command used to build the project. It's already setup so a `make check` will build and run tests, which depend on the project itself, and so will compile and link the project library automatically.

For AppVeyor, we may want to build a config file to be added to version control. Initially the AppVeyor job was setup using the web interface, with no files added to version control. That made for an easy setup process, but it less transparent than a config file. Additionally, a config file would make it easier for a project fork to setup their own CI solutions.

Finally, getting the tests to run on AppVeyor means I'd have an easy way to investigate test failures or warnings that only affect a Windows environment.

**Comment by DanRStevens** [comment]
I took a quick shot at this and then quickly realized Google Test wasn't installed by default in the Linux environments. Further, because of the refusal to ship binaries with the Google Test library, it makes it kind of a pain to install the dependency.

CircleCI may be easiest, by using a custom Dockerfile, based on the currently used `gcc:8` image, but with extra setup to install and compile Google Test. The extra layer needed for the Docker image should be fairly minimal, so it should add much to image download and launch time.

For TravisCI, this seems like more of a pain. TravisCI has no ability to customize the Docker image. If we use the faster booting Docker images, there is no root access. They have a special module to allow installing `apt` packages without root access, so that part is fine, but there is no ability to globally install Google Test libraries afterwards. Hence we would need to compile and store the binaries elsewhere. That could work, in that we could compile them to the project's build folder, and access the libraries from there, it's just a bit awkward, and might require some updates to the build scripts or environment to account for the moved library location.

Alternatively, we could go for the full VM option, rather than the Docker image. That would allow for root access, which enables compiling and installing global libraries for Google Test. Unfortunately, using a full VM adds 30 seconds of startup time to each build, and TravisCI builds are already slow.

**Comment by Brett208** [comment]
I looked up pricing on TravisCI, CircleCI, and AppVeyor. Unfortunately, the absolute cheapest package is $30 / month on AppVeyor. TravisCI and CircleCI are both a fair amount more expensive than this. While I'm not opposed at spending some money if it helps the build process, $360+ / year is a fair amount more than I wanted to see. Too bad there isn't some room for something better than free but less than $100 / year. And I guess this would only get us Windows Builds with AppVeyor and not even Linux.

I think if we stick with the free packages, we should just bite the time bullet and expect long lead build times.

-Brett

**Comment by DanRStevens** [comment]
Yeah, I think we should just stick with the free package for these projects. There are a few ways we could tweak the build time, and it may be worth experimenting with and learning about that topic in its own right.

----

In terms of reducing load, we are duplicating effort between TravisCI and CircleCI, which are both doing g++ Linux builds. We can potentially eliminate some job duplication between them.

We can also look at caching options for dependencies. For the TravisCI builds, that includes Apt packages. For Linux builds on both TravisCI and CircleCI, that includes Google Test.

We could investigate rolling builds. That would require caching. In particular, we cache the build output folder. Essentially we re-use build outputs from the last build, so it only needs to re-build files that have changed. This could leave cruft around when renaming files, since old object files would likely still exist under the old name. I don't see any obvious problems that would affect the build, though caching of stale data could slow down the caching over time.

----

In terms of differences, there are a couple. I noticed TravisCI is setup to do pull request builds and branch builds, while CircleCI is only doing branch builds. The TravisCI builds are building with both g++ and clang, while CircleCI is only building with g++.

Additionally, TravisCI offers a free tier for MacOS builds for open source projects. The other CI providers only have paid options for MacOS builds.

The TravisCI builds use a horribly outdated version of Linux, which requires a lot of setup time to update needed packages. This is done for each build.

----

In terms of where I see things might go, perhaps we could use AppVeyor for Windows builds, CircleCI for Linux builds, and TravisCI for MacOS builds (once the `<filesystem>` issue is sorted out).

To support that, we could add a pull request build to CircleCI, and make it build for both g++ and clang.

----

At any rate, the immediate task is just to find a way to install Google Test to the CI machines and get tests running.

**Comment by DanRStevens** [comment]
Oh, and one more option I forgot to mention. We could potentially run our own CI server. GitHub offers arbitrary web hooks, so it could inform any server we want of new commits that need to be built.

By running our own CI server, we could not only use an optimized Docker image, but also have the server guaranteed to already be caching that image. On CircleCI we have a 35 second startup time (which includes image download), and a 17 second run time. By caching the Docker image, we could reduce that 35 second startup time to probably less than 3 seconds.

Further, running our own server means we could set the number of concurrent jobs it would run. Depending on the hardware we could run as many concurrent tasks as we want. We could probably even exceed the number of cores on the CPU since there's likely going to be some waiting on file I/O.

In particular, I have a server that sits in a basement and is on 24/7. It has plenty of disk space for Docker images, and a dual core processor that could run concurrent builds. The downside being I'm not physically present to restart the machine if it gets knocked out by a power outage or something, which occasionally happens, and can be a few days before I notice and ask someone to restart it.

Would love to learn how to setup something like that, though it's not going to be happening today, or for this issue.

**Comment by DanRStevens** [comment]
This issue has been closed by PR #170 and PR #171, which have now both been merged.
