### ISSUE TITLE
Prevent MapReader from attempting to read a file with wrong extension

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#167]
I was writing a test to ensure that attempting to read a map file with a wrong extension would cause an exception. It currently does not. 

Do we want to allow someone to attempt to load a file with MapReader that does not have either a .map or a .op2 extension? I think my answer is this should cause an exception because it is likely an error and should not attempt to parse, but thought I would bring it up.

-Brett

**Comment by DanRStevens** [comment]
I think we should not rely on the extension in the actual parsing code. This seems like a higher level decision. Forcing it on the parser makes the parsing code more brittle.

Suppose we create an extended map file format some day, with new data, and use a new file extension to distinguish it. We might want to still re-use existing parsing code to parse the common elements.

My thought is, if we pass the parser bad data in a wrong file format, yet have sufficient sanity checks in the parser, we will probably end up with a parsing error anyway. As such, I don't think we need an explicit check on the filename.

**Comment by DanRStevens** [comment]
To add to that, my advice here it to close this as not a bug (in OP2Utility).

You might consider this as a bug in OP2MapImager, though I don't think it's a bug there either. At any rate, the OP2MapImager would be a more appropriate place for this high level of a concern.

**Comment by Brett208** [comment]
Okay, I agree with this overall and will close the issue. Thanks for the comments.
