### ISSUE TITLE
CLM packing should warn about filename truncation

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#17]
CLM internal filenames are limited to 8 characters. During packing, longer filenames are silently truncated to 8 characters. Instead, the user should be informed what is happening. An exception could be raised, allowing the calling code to abort and inform the user.

**Comment by Brett208** [comment]
Example starting in line 158 of ClmFile.cpp using the current Pull Request for x64 fixes:
```
names = StripFilenameExtensions(names);

for (const auto& name : names) {
	if (name.size() > 8) {
		throw std::runtime_error("Filename " + name +  " for packing into archive " + archiveFilename + " must be less than 8 characters in length excluding the extension");
	}
}

// Allowing duplicate names when packing may cause unintended results during binary search and file extraction.
CheckSortedContainerForDuplicateNames(names);
```

**Comment by DanRStevens** [comment]
Good catch on the bad logic.

The exception looks like a workable solution. One nitpick, the exception message wording "less than 8 characters" is slightly off. Not greater than 8 characters means less than or equal to 8 characters. Maybe phrase as "at most 8 characters".

The comment below contains a slight error. The CLM files do not use a binary search. Maybe drop the reference to "binary".

**Comment by Brett208** [comment]
Agreed with the update for the exception message.

The last comment in the block is trying to highlight that the binary search performed by Outpost 2 may not match the results of the linear search done by Outpost Utility. But it doesn't really say that either. I like the idea of just dropping the word binary and then the confusion will be lifted.

I'll implement this code in a new branch soon to patch the security hole. After that I would be happy closing this issue. If you want to leave this issue open until someday in the future the API is updated to allow a choice in truncation, that sounds fine to me as well.

-Brett

**Comment by DanRStevens** [comment]
Sounds good. Let's try and close things off. We can always open a new issue if we change our minds later.

I think an error for truncation makes sense, since there is no way to not truncate.

A warning for duplicates makes sense, since you could actually create a file with duplicates, and might want to process one for forensic reasons.

**Comment by Brett208** [comment]
@DanRStevens,

How would you feel about updating the functions CreateArchive and Repack to include a Boolean value that allows duplicate name inclusion. This variable will default to false. This way if duplicate names are desired for testing purposes, it can be intentionally set to true but will otherwise not allow duplicate names in archive packing. I think this idea appeals to me more than issuing a warning message via cerr.

```
// Setting duplicate names to true allows packing archives containing 2 or more entries with the same name. duplicateNames should remain false unless intentionally testing the effects of duplicate entries.
static void CreateArchive(const std::string& archiveFilename, std::vector<std::string> filesToPack, bool duplicateNames = false); 
virtual void Repack(bool duplicateNames = false) = 0;
```

Thanks,
Brett

**Comment by DanRStevens** [comment]
You're right, issuing an error through cerr is not very clean. I would like to avoid that, especially deep in library code. To properly handle warnings, we should have a way of reporting them to the caller, so the caller can decide how to display them.

My experience with Boolean parameters is they are not very self documenting at the point of call. I prefer to avoid them for one-off flags like this. Curiously, The Clean Code Collection makes a similar recommendation. With that said, I'm not totally against the idea either. I think if we wanted to include an extra parameter, perhaps we should use a 2-valued enum. We can still have a default value, and the point of call would be much more self documenting when passing a non-default or explicit value.

I should also point out that a new parameter is not useful until code is added to interface with it, such as by adding a new command line flag.

Questionable if `Repack` needs the parameter. Though also questionable if we should even still include a `Repack` method. That's getting off topic though.

At any rate, I'm causing distraction. The duplicate name concern is outside the scope of the original issue here, which is name truncation. I'd be fine with leaving things as exceptions for now and closing this off. Having names that are too large does seem like a hard error, so exceptions are fine here. If duplicate names cause an exception, I can live with that for now.
