### ISSUE TITLE
Implement WritePartial

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#172]
I just noticed the Stream::Writer class has no corresponding WritePartial method. Should we implement this? It seems easy to do, though would need to be implemented in all derived classes.

I don't think we have any immediate need for it. Mostly it would be for symmetry in the API. Potential other users of the stream library might find it useful.

For stream copying, I used ReadPartial on one side, and Write on the other side. Seemed to make sense that way, since as there was a bit of an assumption that all data read could be written.

If we implement this, it should be a low priority task. API would look like:
```cpp
virtual std::size_t WritePartial(const void* buffer, std::size_t size);
```

**Comment by Brett208** [comment]
I think it should be added to match ReadPartial as pointed out.

-Brett

**Comment by DanRStevens** [comment]
I was looking back at this. I'm thinking the maintenance cost of adding this is not worth it. I can't think of any compelling reason to add it, and having it adds a burden on all derived classes.

In terms of pairing and symmetry, the `ReadPartial` method of the `Reader` class more or less pairs with the `Write(Reader&)` overload of the `Writer` class.

I'm going to close this as don't fix.
