### ISSUE TITLE
Define how pixel containers are formed in memory

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#195]
Currently, we have 2 functions for writing a bitmap. Option one assumes a pitch of 4 is already included in the container (each row of pixels is rounded up to the next 4 byte interval). Option two assumes no pitch is included and manually adds a buffer out to the next 4 byte interval.

First question: Is option 2 really an expected format at all? Or will all pixel containers be passed including pitch?

Assuming that pixels may be passed without the buffer, Option two gets complicated when dealing with a bit count less than 8. For example, if assume a 1 bit count image with dimensions of 4x2 (width x height). Assume the pixel data is: `0b1000 1000`. How should we expect this to be passed into the writer?

 * 1 byte total. `0b1000 1000`
 * 1 byte per row: `0b1000 0000, 1000 0000`

If we assume pixels do not share bytes between rows, the calculations become a lot easier.

Relevant documentation: https://en.wikipedia.org/wiki/BMP_file_format

> Padding bytes (not necessarily 0) must be appended to the end of the rows in order to bring up the length of the rows to a multiple of four bytes. When the pixel array is loaded into memory, each row must begin at a memory address that is a multiple of 4. This address/offset restriction is mandatory only for Pixel Arrays loaded in memory. For file storage purposes, only the size of each row must be a multiple of 4 bytes while the file offset can be arbitrary.[4] A 24-bit bitmap with Width=1, would have 3 bytes of data per row (blue, green, red) and 1 byte of padding, while Width=2 would have 2 bytes of padding, Width=3 would have 3 bytes of padding, and Width=4 would not have any padding at all.

**Comment by DanRStevens** [comment]
I would say option 2 is not expected. Any required padding can be added in memory when the bitmap buffers are created. As for the file format, you can expect a valid file to already include the padding. At least that should be true for true color images. I don't believe the padding is required for palettized/indexed images.

I'm uncertain of the padding requires for monochrome bitmaps. Perhaps save a 1 pixel wide column of white in MSPaint and see what padding and structure it uses.

**Comment by Brett208** [comment]
I just created a 1 pixel wide x 2 pixel tall monochrome BMP using MSPaint (Windows 10 version).  Hopefully the ghetto HxD markup below is useful. GitHub does not allow attaching BMPs to posts or I would have included the original file as well.

Even though the image was 1 pixel wide, MSPaint allocated 4 bytes per row for pixels. Even though only 1 palette color was used, MSPaint allocated both palette colors. I made the same file using our code base. A couple of bugs were encountered that I need to push a fix for. After those bugs were resolved, we produced a BMP that exactly matches MSPaint's version, except that we are setting the Image Size as 0 and MS Paint set it as 8. This doesn't affect MS Paint's ability to read our file.

[1wide2TallMonoChromeMSPaint.txt](https://github.com/OutpostUniverse/OP2Utility/files/2413417/1wide2TallMonoChromeMSPaint.txt)

```
B  M  FileSize=70 Resd1 Resd2 PixOffset62 HeadrSize40 ImgWidth= 1 ImgHe
42 4D 46 00 00 00 00 00 00 00 3E 00 00 00 28 00 00 00 01 00 00 00 02 00

ight2 Plns1 BitC1 Compression ImageSize=8 xResolution yResolution UsdCo
00 00 01 00 01 00 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00

lrMap ImpColrCoun Palette   0 Palette   1 Pixel 0     Pixel 1
00 00 00 00 00 00 00 00 00 00 FF FF FF 00 80 00 00 00 80 00 00 00
```

Okay, so what do you think of just eliminating the current IndexedBmp::Write function? This would mean you must provide the pixels including a 4 byte pitch. (Perhaps a future version could allow other forms of  pitch). 

I would actually probably rename the current function `WritePixelsIncludingPadding` as just `Write` and annotate the pixels container as requiring 4 byte pitch.

Thanks,
Brett

**Comment by Brett208** [comment]
I think we are generally in agreement. I'll plan to make these changes.

-Brett
