### ISSUE TITLE
Improve MSVC gtest/gmock dependency

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#247]
We need to find a gtest dependency that allows us to use gmock on MSVC builds and set MSVC compilations as C++17 compliant. C++17 compliance is required for nesting namespace declarations.

I have continued working with vcpkg. I have OP2Utility compiling locally with the following settings:
 * vcpkg x86 and x64 gtest packages installed (no static gtest versions available as far as I can tell)
 * gtest nuget package uninstalled
 * preprocessor directive _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING removed
 * Preprocessor directive GTEST_LINKED_AS_SHARED_LIBRARY was added (I think we are not building this as shared, but gmock doesn't seem to work unless I set it)
 * gmock code in XFile.test.cpp uncommented (see bullet above, gmock is working with vcpkg unlike nuget package)
 * C++17 flag set in both OP2Utility and OP2UtilityTest (Could not set this property using Nuget gtest)
 * Code compiles in both debug and release mode in both x86 and x64 without error or warning. However, tests only run in release modes. Debug mode gives me a chime, brings up an empty console window and seems to just sit there. Below is the output log: 

```
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Users\Brett\Documents\OutpostUniverseGitHub\OP2Utility\x86\Debug\OP2UtilityTest.exe'. Symbols loaded.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Users\Brett\Documents\OutpostUniverseGitHub\OP2Utility\x86\Debug\gmockd.dll'. Symbols loaded.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140d.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. Cannot find or open the PDB file.
Debug Assertion Failed!

Program: ...OutpostUniverseGitHub\OP2Utility\x86\Debug\OP2UtilityTest.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 996

Expression: __acrt_first_block == header

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. Cannot find or open the PDB file.
'OP2UtilityTest.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. Cannot find or open the PDB file.
The thread 0xaf0 has exited with code 0 (0x0).
```

I'm not really sure how to (Press Retry to debug the application). 

Any help on this would be appreciated. I feel close to getting vcpkg's gtest install to work, but I'm stuck and doubt that I will make much more progress on my own.

-Brett

**Comment by DanRStevens** [comment]
Thank you for looking into this.

Can you push the changes to a branch? It looks like there is some mixing of debug and release builds. The two are likely binary incompatible, so if you force linking of the wrong one, bad things can happen. It's unclear to me if this is a static library or DLL build of Google Test.

**Comment by Brett208** [comment]
Added PR #248 as requested.

There doesn't appear to be a static build of Google Test available for install via vcpkg (I'm new to vcpkg so may have missed it).

See the appveyor build for details. It passed with release and failed for debug, so I guess that rules out my local machine being the problem.

-Brett
