### ISSUE TITLE
Remove using Palette8Bit

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#258]
To ease reading, we are currently using the following type:

```C++
using Palette8Bit = std::array<Color, 256>;
```

It facilitates a little easier reading of the ArtFile because we do not have to dynamically resize the palette for each read.

Since Bitmaps could have other sized palettes, I think we should consider removing the type and just using a std::vector<Color> to represent the palette. This will take a bit more work to read/write from and ArtFile, but I think will facilitate easier transfer to a normal bitmap file.

**Comment by DanRStevens** [comment]
I think you may be right.

**Comment by Brett208** [comment]
`using Palette8Bit` was moved out of Color.h (generic bitmap code) and into PaletteHeader.h (specific to Outpost 2 sprite loading). I think this is acceptable to close this issue.
