### ISSUE TITLE
Remove unused ArtFile variable from PaletteHeader constructor

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#283]
Currenty two constructor overloads exist for PaletteHeader. 

```C++
PaletteHeader::PaletteHeader() : remainingTagCount(0) {}
PaletteHeader::PaletteHeader(const ArtFile& artFile)  : remainingTagCount(1)
```

The first one allows initializing the struct with minimum work but still making it viable. The second one initializes the header with regular values (which oddly enough does not require any input from ArtFile).

Perhaps changing the second constructor into a static function that returns a populated PaletteHeader would be more appropriate. Then the dummy ArtFile variable would no longer be needed.

**Comment by DanRStevens** [comment]
That sounds like a good plan.
