### ISSUE TITLE
Drop TravisCI support

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#327]
It seems TravisCI is still doing builds. Perhaps we should turn that off and remove the `.travis.yml` file.

We haven't been getting TravisCI build status reports on GitHub in ages, so we're really not using TravisCI. Plus, maintaining it was kind of a pain. The experience and build time is much better with CircleCI.

Build history:
https://travis-ci.org/OutpostUniverse/OP2Utility/builds

**Comment by Brett208** [comment]
Sounds to me.
