### ISSUE TITLE
Unmaintained CMakeLists.txt

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#344]
We have a CMakeLists.txt file in the root folder that appears to be unmaintained. In particular, it specifies C++14, though I believe the project has long relied on C++17. Perhaps we should consider removing the file if we don't plan to maintain it.

**Comment by Brett208** [comment]
It was an experiment. We seemed happier just having a custom makefile and custom visual studio project over trying to auto generate the different build paths. 

I'm ok with it being removed.
