### ISSUE TITLE
Switch StreamReader/Writer to use void* when representing a buffer

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#36]
Currently char* is used to represent buffers. Perhaps void* would be more appropriate?

I'm not actually certain what the pros and cons of each choice are.

**Comment by DanRStevens** [comment]
It's not a big difference in semantics, though `void*` is a little more correct. With `void*` it is a pointer to an untyped memory location. A buffer can represent anything, and with streams the data is sliced into objects of a variety of types. With `char*` there's a suggestion the buffer points to characters.

As characters are the closest datatype to a byte, it's still fairly natural to represent buffers as `char*`. It also allows for the convenience of pointer arithmetic, such as `buffer + offset`. In C/C++, the syntax `pointer + number` actually represents the address `pointer + number * sizeof(dataType)`. Hence if the datatype is `char`, the arithmetic works out nicely in terms of bytes. If you try that with a `void*` it's an error as there is no well defined `sizeof` to work with. You would need to cast to another pointer type to perform arithmetic.

In C, you can copy both ways between `void*` and other pointer types without casting. In C++ it's a little more restrictive, in that you can copy into a `void*` without casting, but you need a cast to convert back out of it.

Also noteworthy is that C did not originally have the `void*` type, and so `char*` was the standard way to represent a pointer to a buffer before the ISO/ANSI C standard introduced `void*` as a type.

The trade-offs:
`char*`: allows pointer arithmetic without casting, but requires casting for type conversion.
`void*`: type conversions are cast-free (both ways for C, to `void*` for C++), but requires casting for pointer arithmetic

For an API, having `void*` in the interface simplifies usage for the caller, while pointer arithmetic can be done internally with casting, making for a nicer interface.

Example:
```
#include <iostream>

void Func(void* data) {
  std::cout << "void* data = " << std::hex << data << std::endl;
}

int main() {
  char buff1[4];
  int buff2[4];

  // Func can take pointers to any type without casting
  Func(&buff1);
  Func(&buff2);

  // One-way cast-free type conversions
  void* ptr1 = &buff1;
  //char* ptr2 = ptr1; // Error with default checks, warning with -fpermissive (g++)

  return 0;
}
```

**Comment by Brett208** [comment]
@DanRStevens, Thank you for quality writeup on the issue. 

In practice using StreamReader/Writer in the current code base, I tend to end up casting often to char*. Removing the char* cast everywhere would be nice. I don't tend to perform pointer arithmetic very often (if ever), so switching to void* seems like a win in readability and reduced typing.

-Brett
