### ISSUE TITLE
Review StreamReader/Writer Read/Write template functions to autodetect sizeof buffer

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#37]
Currently, FileStreamReader, MemoryStreamReader, FileStreamWriter, and MemoryStreamWriter contain a template function to autodetect the type being read into/out of and assign the size automatically. 

These functions cannot be used when referencing the base classes StreamReader, StreamWriter, SeekableStreamReader, and SeekableStreamWriter. I do not believe C++ supports virtual functions as being templates.

Perhaps there is a solution that would allow calling the template based Read/Write from the base classes that I am missing.

**Comment by DanRStevens** [comment]
Just put the template methods in the base class. They don't need to be virtual. They can and should be inline, as they are small wrappers that just delegate to the virtual methods.

In terms of the generated assembly code, calling the templates should be identical to calling the virtual methods directly with more verbose code to indicate buffer sizes.
