### ISSUE TITLE
Typo 'expectedLenth' instead of 'expectedLength' in TilesetLoader.cpp - Line 177

### ISSUE THREAD

**Issue by TechCor8** [OutpostUniverse/OP2Utility#398]
https://github.com/OutpostUniverse/OP2Utility/blob/de2e73d68a7f8ddfcdc9f61189cd2b40c558a290/src/Sprite/TilesetLoader.cpp#L177

Minor spelling issue.

**Comment by DanRStevens** [comment]
Ahh, thank you.
