### ISSUE TITLE
Split Stream related classes into their own files, and organize into subfolder

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#43]
The Stream classes are currently all lumped together in StreamReader/StreamWriter .h/.cpp files. They should be split into their own files for each class. The resulting files should be organized into a Streams folder.

**Comment by Brett208** [comment]
I'd like to handle this task. It will make integrating with the Visual Studio project and filter file easier.

Streams sounds better for the folder name than my idea of Serialization.

If we are close to resolving the current open branches enhancing StreamReader/Writer, I'll wait for them to close as it will cause less merge conflicts. 

Thanks,
Brett

**Comment by DanRStevens** [comment]
I think you're right, you may be better able to handle this one. I hadn't originally considered the Visual Studio project files.

I updated and pushed all my current changes, except for the template move change, which remains broken. It's trivial though, so we can just redo that after a refactor, assuming we find a way to fix it.
