### ISSUE TITLE
Refactor variables in struct VolFile::CreateVolumeInfo

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#56]
Refactor VolFile::CreateVolumeInfo and VolFile::IndexEntry to use C++11 containers to reduce custom memory management. Use fixed size type fields to improve compatibility of reading/writing data with different compilers. 

Within CreateVolumeInfo, switch the following fields to std::vector: 
 - IndexEntry *indexEntry;
 - int *fileNameLength;
 - HANDLE *fileHandle;

Within CreateVolumeInfo, make the following fields an unsigned fixed size type: 
 - int stringTableLength;
 - int indexTableLength;
 - int paddedStringTableLength;
 - int paddedIndexTableLength;

Within VolFile::IndexEntry, make the following fields an unsigned fixed size type: 
 - unsigned int fileNameOffset;
 - unsigned int dataBlockOffset;
 - int fileSize;

**Comment by DanRStevens** [comment]
I agree.

Eliminating manual memory management will be a plus.

The `fileNameLength` array can be removed now, I think, with little work. The values should match the corresponding string length plus null byte: `fileName.size() + 1`

The table lengths are definitely unsigned. It may make sense to make methods to compute them. Though a quick scan of existing code shows quite a few uses, so it may make sense to continue caching those values for speed.

The IndexEntry fields definitely need to become fixed length, and unsigned.

**Comment by Brett208** [comment]
I plan to pull out the HANDLE code from IndexEntry next and will also generally work the rest of this issue.
