### ISSUE TITLE
Simplify VolFile by assuming that files will not be added or removed without a full repack

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#78]
Volumes can support removing files, however it tends to leave excess memory in the volume that is no longer used. It is probably better to repack to reduce the size of the volume when removing a file.

Additionally, when attempting to add a file to a volume, it would need to be added alphabetically to support a binary search. There would also need to be empty space large enough to add the file. 

Neither use case is tested for right now and testing for these use cases would add additional burden to the library with little gain.

---

In particular, ReadPackedFileCount could probably be simplified/improved.

**Comment by DanRStevens** [comment]
Agreed that we don't need to support creating archives with extra padding space, or in-place add/delete operations. We can gut code to support output of padding, though we should maintain code to handle processing of padded input.

Off topic side note: One point of clarification, the filename string table, and the actual file contents can go pretty much anywhere, in any order, with arbitrary padding around it. You could just append a filename to the string table, and you can append new file contents to the archive. It's only the index table that needs to be sorted for the binary search to work.

Really off topic side note: If you want to get really fancy, if one filename is a suffix of another, they can overlap in the string table. Two index entries can point to two different starting characters, which eventually overlap and are terminated by the same null. Space savings for the win! :grin:

**Comment by Brett208** [comment]
I think this issue can just be closed. We already do not allow adding/removing files without doing a full repack. We will want to retain the ability to read a volume with padding at the end of the string table and the index entries since there are production volumes that have both. This is already supported as well. See #77 for a possible small improvement to how IndexEntries are read.

**Comment by DanRStevens** [comment]
Ok, sounds good to me.
