### ISSUE TITLE
Switch to fixed width types on stream related variables in clmFile

### ISSUE THREAD

**Issue by Brett208** [OutpostUniverse/OP2Utility#82]
The following changes should be made to ClmFile to improve stream read/write compatibility with different compilers.

Set IndexEntry::dataOffset and dataLength to uint32_t
```
struct IndexEntry
{
	std::array<char, 8> fileName;
	unsigned int dataOffset;
	unsigned int dataLength;

	std::string GetFileName() const;
};
```

int ClmFile::FindChunk should return a uint32_t and throw an error if Chunk is not found instead of returning -1

In ClmFile::ReadAlWaveHeaders, fmtChunkLength & dataChunkLength should be uint32_t instead of int.
```
// Read the format tag
int fmtChunkLength = FindChunk(tagFMT_, *filesToPackReaders[i]);
. . .
// Find the start of the data
int dataChunkLength = FindChunk(tagDATA, *filesToPackReaders[i]);
```

Variable CLM_WRITE_SIZE can be removed (no longer referenced)
```const uint32_t CLM_WRITE_SIZE = 0x00020000;```

**Comment by Brett208** [comment]
I'll take this workload on this weekend.

**Comment by DanRStevens** [comment]
Agreed on all counts.

After all these recent changes, I was actually getting a warning from Clang about CLM_WRITE_SIZE not being used.
