### ISSUE TITLE
Chained calls to `append` produce compile errors on Linux

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#86]
On Linux, both g++ and clang give errors for chained calls to `append`:
https://github.com/OutpostUniverse/OP2Utility/blob/eb764f239c8f6b8375a5b9697c0d22b36ad622e3/XFile.cpp#L144-L148

The error is:
```
XFile.cpp:144:42: error: no matching member function for call to 'append'
                return fs::path().append(subDirectory).append(filename)....
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/experimental/fs_path.h:223:7: note: 
      candidate template ignored: requirement '__and_<__not_<is_same<path, path>
      >, __constructible_from<path, void> >::value' was not satisfied [with
      _Source = std::experimental::filesystem::v1::__cxx11::path]
      append(_Source const& __source)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/experimental/fs_path.h:231:7: note: 
      candidate function template not viable: requires 2 arguments, but 1 was
      provided
      append(_InputIterator __first, _InputIterator __last)
      ^
XFile.cpp:148:32: error: no matching member function for call to 'append'
        return p.append(subDirectory).append(filename).string();
               ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/experimental/fs_path.h:223:7: note: 
      candidate template ignored: requirement '__and_<__not_<is_same<path, path>
      >, __constructible_from<path, void> >::value' was not satisfied [with
      _Source = std::experimental::filesystem::v1::__cxx11::path]
      append(_Source const& __source)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/experimental/fs_path.h:231:7: note: 
      candidate function template not viable: requires 2 arguments, but 1 was
      provided
      append(_InputIterator __first, _InputIterator __last)
      ^
```

In both cases it seems to be complaining about the second chained `append` call. Looks like a template guard is preventing the expected method from being selected. I haven't yet figured out why. I'm wondering if it might be a version difference, either between standards, or between platform. I'll look more into it.

**Comment by Brett208** [comment]
Problems like this are good reasons to avoid using experimental libraries. If only there was a good alternative in the standard library.

If you feel like I used append wrong here or we just need to change it to work on both systems, I have no issues at all with it.

**Comment by DanRStevens** [comment]
Hmm, I missed a subtle point the first time around. The `append` method is equivalent to `operator /=`. It is not equivalent to `operator /`. That is, it modifies the source object on the left, rather than returns a newly constructed object.

Chaining calls to `append` is like writing this weird looking code:
```
		return (fs::path() /= subDirectory /= filename).string();
```

Re-writing as follows seems to work:
```
		return (fs::path() / subDirectory / filename).string();
```

Granted, there are probably better ways to write the code. For this line, perhaps not start with an empty path, so a double append isn't needed. Though a deeper solution might question why we even have this whole method, and if perhaps the calling code could have been designed differently. I find the existence of this method a bit strange.

The proposed solution doesn't answer why the compiler rejected the original code. I'm still curious about that.
