### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#89]
We should add unit tests for this library.

Unit tests will help ensure nothing breaks during refactoring. It's also a good quality marker for a library that may be re-used by other people. Finally, writing such tests will give us a good chance to review a lot of the code and address any quality issues.

**Comment by Brett208** [comment]
I've been eying two options here. GoogleTest and CTest. I had tried to find some info comparing the 2 options a couple of months ago, but CTest didn't seem to be well reviewed yet.

CTest seems simpler to use, especially if we do go with CMake. I did see there were tutorials on how to mate CMake with GoogleTest. GoogleTest/Mock is probably going to be more flexible but I'm guessing more difficult to implement.

If CTest isn't significantly used, then it might be a poor choice, but I don't have any data on how popular it is.

I'd be open to other options as well...

I think my general priority list is getting the codebase reliably compiling on both platforms first before adding the complexity of a unit test project.

**Comment by DanRStevens** [comment]
I did a bit of reading tonight. It appears CTest is a test driver for CMake, rather than a testing framework. It seems to have support for running tests using the GoogleTest framework.

I also came across a Wikipedia [List of Unit Testing Frameworks](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C++). The C++ section was quite extensive. Far more options than I'd care to research. At some point we need to just select something and try it out.

I think I'm leaning towards just using GoogleTest.

**Comment by Brett208** [comment]
I did some more reading on CTest a while back, and yes it has some support for GoogleTest. I'm not sure it is as robust as we would want though? 

GoogleTest is on the top of my list for test frameworks as well. It seems well documented, well used, and mature. We should probably just go with it for now.

Since we don't seem too sure about CMake at this time, it might be better to directly integrate the testing framework with the Visual Studio solution and makefile. We can always move the test framework to use CTest later if we go that route.

It looks like Google Test is maintained in a Git repository on GitHub. We might be able to just add it as a sub-module to the OP2Utility repository. I have not done any research on this yet though.

> These are the base requirements to build and use Google Test from a source package (as described below):
> 
>     GNU-compatible Make or gmake
>     POSIX-standard shell
>     POSIX(-2) Regular Expressions (regex.h)
>     A C++98-standard-compliant compiler
> 
> Windows Requirements
> 
>     Microsoft Visual C++ 2015 or newer
> 

We meet the Windows Requirement. I assume the Linux requirements are met as well?

-Brett

**Comment by DanRStevens** [comment]
So, technical challenges of getting Google Test code to compile and run aside, I think there were some organizational challenges that were causing me to avoid getting started. In particular, what is the typical layout of the test code. The Google Test library doesn't require any specific layout, and the docs don't suggest any particular layout. Such details are omitted from the examples.

Searching the internet, there seems to be a few common layouts used: having a parallel sub-tree distinct from the source folder, having a test folder within each source folder to hold the test code, heaving the test files just appear alongside the source files, and (not so much for C++, but for other languages) putting the test code right into the source files.

I believe the most common layout is to have a separate parallel subtree, distinct from the project "src" folder". I figure this is a good option to go with. Conceptually this makes a lot of sense, since technically the test code is a separate project, which depends on the library being tested. When distributing the library, end users probably won't care to compile or run the test project. The test project is intended more for library developers. There are various names for the test folder, such as "test", "tests", and "spec". I had noticed "test" a little more often than the others, and I figure that's probably the best name to use.

In case you've got a preference, I wouldn't mind the option where tests are placed alongside the source. With that layout, you'd need to filter the source when compiling to split the project code from the test code. That could be accomplished fairly easily with consistent naming and file glob patterns. A benefit to that approach is the code and the tests for the code appear next to each other in a directory listing, which can make it easier to jump from one to the other. Though some IDEs have plugins that allow you to easily jump from one file to the other, with any layout, assuming some predictable regular naming scheme.

As for file naming scheme, there is some variation there too. One scheme I saw was to name the tests "*.test.cpp". Another was to prefix the filenames with "test" (or "Test", "test-", "test_"). I think I prefer the suffix. It's similar to a normal extension, (an extended extension?) so nicely summarizes the type of data in the file, while also still identifying it as a C++ source file. It also means if you mix the source and tests in the same folder, they sort nicely into related groups. Using a prefix, all the test files would sort to position "t", leaving you with a big chunk of test files in the middle of the source files. In case we change layouts at some point, it would be easier and cleaner to use the suffix form.

----

Suggested example layout:
```
src/file1.cpp
src/file2.cpp
src/subfolder/file3.cpp
test/file1.test.cpp
test/file2.test.cpp
test/subfolder/file3.test.cpp
```

**Comment by Brett208** [comment]
I think placing the test files in a directory called test that mirrors the source directory sounds like the best plan. *.test.cpp seems like a good naming convention as well.

At first I was thinking they should exist in folder with the source code. However Visual Studio will separate them in the IDE into different virtual folders anyways since they will belong to different projects.

Hopefully if the tests are clean and succinct, they will provide some natural documentation on how to use the public members of the library.

Thanks for putting time into researching the common naming conventions.

**Comment by DanRStevens** [comment]
I worked on some `makefile` updates today, so it could build the test runner and run the tests.

I was able to successfully compile and run tests using g++.

----

I ran firsthand into the compiler setting difficulty with Google Test. This happened because I'd set the `makefile` to use clang-6.0 by default, if no compiler (`CXX` variable) was specified. When I'd built and installed Google Test, I'd compiled with the system default compiler, which was g++. Hence the compiler mismatch, which resulted in a ton of linker error messages.

While investigating, I found there are incompatibilities between two standard library implementations. The libstdc++ implementation ships with g++, while libc++ implementation ships with clang++. If an API exports symbols that use the standard library, (think non-trivial symbols which contain `std::`), it can create problems. Naturally runtime problems due to incompatible class layouts would be awful, so instead the programmer is protected by having different name mangling between the two. Thus you end up with link errors instead.

On a related note, I found an article discussing [ABI changes for g++ between c++98 and c++11](https://gcc.gnu.org/wiki/Cxx11AbiCompatibility).

As the compile time for Google Test isn't very long, perhaps it can become part of the build process for the tests.

I also ran into a file order dependency and filename issues with my additions to the makefile. Looks like there might be a few small issues to work out still.

**Comment by Brett208** [comment]
I have GoogleTest working for all combinations of x86, x64, debug, and release configurations on Windows. 19 warnings are issued by MSVC when compiling GoogleTest that I'm unsure of how to deal with, but they do not seem to affect the use of the Unit Test library at this time. 

I'm placing the Windows Test project file inside of the /test folder for now. This is a bit different since the OP2Utility project file is in root instead of /src. I think the standard Microsoft solution would be to have OP2Utility project files in a subdirectory like /src with the OP2Utility solution file in the root directory.

Perhaps tomorrow it will be ready to commit to a branch.

-Brett

**Comment by Brett208** [comment]
I'd like to discuss test organization a little. How much ground should an individual test cover? For example, we have short macros like the following that each test a very small and discrete part of the code.

```
TEST_F(SimpleMemoryStreamReader, SeekRelativeOutOfBoundsEndPreservesPosition) {
	auto position = stream.Position();
	EXPECT_THROW(stream.SeekRelative(6), std::runtime_error);
	EXPECT_EQ(position, stream.Position());
}

TEST_F(SimpleMemoryStreamReader, SeekRelativeOutOfBoundsBeginningPreservesPosition) {
	auto position = stream.Position();
	EXPECT_THROW(stream.SeekRelative(-1), std::runtime_error);
	EXPECT_EQ(position, stream.Position());
}
```

These could be combined like this:

TEST_F(SimpleMemoryStreamReader, SeekRelativeOutOfBoundsPreservesPosition) {
	auto position = stream.Position();

	EXPECT_THROW(stream.SeekRelative(6), std::runtime_error);
	EXPECT_EQ(position, stream.Position());

	EXPECT_THROW(stream.SeekRelative(-1), std::runtime_error);
	EXPECT_EQ(position, stream.Position());

        EXPECT_EQ(stream.Length(), buffer.size());

	EXPECT_EQ(stream.Position(), 0);

	std::array<int, 6> destinationBuffer;

	auto position = stream.Position();
	EXPECT_THROW(stream.Read(destinationBuffer), std::runtime_error);
	EXPECT_EQ(position, stream.Position());

	stream.Read(&destinationBuffer[0], 1);
	EXPECT_EQ(stream.Position(), 1);
}

The benefit from the second is that the number of test objects created is less. Also overall lines of code are reduced. But, the test sort of run together and are hard to understand. The answer should probably be somewhere in the middle I suppose.

-Brett

**Comment by DanRStevens** [comment]
A very good question.

Generally, the smaller the better. A test should try to focus on one thing, and include just enough to test some small well defined concept.

In particular, you want to avoid accidental side effects. If one of the earlier assertions fails, that could cascade into a series of failures for later assertions due to bad object state.

For the stream position, it makes sense to test that an operation both causes an exception to be thrown, and that the stream position has not changed as a result. The two checks are tied together. As for independent seek operations in the same unit test, there is a chance that one will affect the other. If seeking into the file doesn't cause an exception, then seeking backwards might then move to a valid position and also not cause an exception. Hence you'd have a cascade of failures in the test results.

Of course that's not to say I never violate that ideal. I frequently wonder what's a good place to break up test methods.

**Comment by DanRStevens** [comment]
Ahh yes. I just commented on that in your latest PR. That's been big in my mind, particularly for the Stream code.

In the [Advanced Google Test Topics](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md), starting a little over half-way through the (rather long) document, there is a section titled [Value-Parameterized Tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#value-parameterized-tests), which starts the topic of re-using test code. It's a good intro, but it's not quite the section we want. The value parameterized tests are the same test, but with variable data.

A little later on, there is a section on [Typed Tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#typed-tests). This is the same tests but for multiple classes. This is almost what we want. The section is described: "Suppose you have multiple implementations of the same interface and want to make sure that all of them satisfy some common requirements." You use the `TYPED_TEST()` macro to define the tests, and instantiate them for a list of types with the `TYPED_TEST_CASE()` macro. The problem being, the list of types is specified all once together. That's fine when the possible types are fixed, but doesn't work so well for an extensible class hierarchy that must fulfill an interface.

Finally there is the section on [Type-Parameterized Tests](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#type-parameterized-tests). These use the `TYPED_TEST_P()` macro to define the tests. They then need they `REGISTER_TYPED_TEST_CASE_P()` macro to register the tests, which must be done before instantiating them. Registration requires listing all the tests in that test suite. Finally, you instantiate the test suite for any given type you want with the `INSTANTIATE_TYPED_TEST_CASE_P()` macro.

I think I need to give those sections another quick read through to really understand them.

**Comment by DanRStevens** [comment]
I missed a point in my previous summary. Namely, calling the `TYPED_TEST_CASE_P()` macro.

For a Type-Parameterized Test, you want to first define a fixture class. Then call the `TYPED_TEST_CASE_P()` macro to declare that you will define a type-parameterized test case using the fixture as a base. Then use `TYPED_TEST_P()` macros to define the various tests. Then call the `REGISTER_TYPED_TEST_CASE_P()` macro to collect all the various test into a test case. That completes the generic definition of a type-parameterized test case. All of the above should go in a header file associated with the interface.

Finally, you instantiate the tests for a specific types by calling the `INSTANTIATE_TYPED_TEST_CASE_P()` macro for various concrete implementations of that type. That is, you call it for each of the classes that implements the given interface. This code should go in the implementation file for the tests of the respective classes.

**Comment by DanRStevens** [comment]
I'm thinking we should close this issue. Testing seems to be reasonably established now. If there are specific areas where we need to build up tests, we can create a more focused issue to address that one area.
