### ISSUE TITLE
FileStreamReader member initializer list does not match actual initialization order

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/OP2Utility#91]
On Linux, there is a warning with g++ and clang for the member initializer list in FileStreamReader constructor:
```
g++ -MT build/obj/Streams/MemoryStreamWriter.o -MMD -MP -MF build/deps/Streams/MemoryStreamWriter.Td -std=c++14 -g -Wall -Wno-unknown-pragmas  -c -o build/obj/Streams/MemoryStreamWriter.o Streams/MemoryStreamWriter.cpp
In file included from Streams/FileStreamReader.cpp:1:0:
Streams/FileStreamReader.h: In constructor ‘FileStreamReader::FileStreamReader(std::__cxx11::string)’:
Streams/FileStreamReader.h:29:20: warning: ‘FileStreamReader::filename’ will be initialized after [-Wreorder]
  const std::string filename;
                    ^
Streams/FileStreamReader.h:28:16: warning:   ‘std::ifstream FileStreamReader::file’ [-Wreorder]
  std::ifstream file;
                ^
Streams/FileStreamReader.cpp:5:1: warning:   when initialized here [-Wreorder]
 FileStreamReader::FileStreamReader(std::string filename) : 
 ^
```

One fix is to swap the declaration order of the fields:
```
private:
	const std::string filename;
	std::ifstream file;
```

The other alternative is to swap the order in the member initializer list:
```
	//filename(filename), file(filename, std::ios::in | std::ios::binary)
	file(filename, std::ios::in | std::ios::binary), filename(filename)
```

Either way, the declaration order should then match the listed initialization order. Or in other words, the listed initialization order will then match the actual initialization order.

Any preference?

**Comment by Brett208** [comment]
I hadn't thought about class member variable destruction order until it was brought up in an earlier thread, which is probably why this is written how it is. 

It would make more sense to me to construct the filename first, then construct the std::ifstream. Then for destruction, destroy the std::ifstream first, then the filename. (I recognize that in practice the ifstream doesn't actually depend on the class level filename, but this seems more logical to me?)

**Comment by Brett208** [comment]
A few other details that can be added to the issue as they touch similar parts of the code. I'd like to match FileStreamReader and FileStreamWriter closer with variable names and initialization list. 

 - Construct the FileStreamWriter's ifstream in the member initialization list (mirroring FileStreamReader)
 - Switch the order of FileStreamWriter's class level variables filename and ifstream to match FileStreamReader as mention above.
 - Match the name of the class level ifstream to match in both FileStreamReader and FileStreamWriter. I think using the name fileStream makes more sense to me, but I don't mind it being file or something else either.

**Comment by DanRStevens** [comment]
Ok, I think I have the same inclination here too. I'll put together a patch. I'll re-order the member variable declarations to match the intializer list. I'll also look into renaming member variables to match across classes in the stream library.
